/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import Data.PersonaDAO;
import Data.TipoPersonaDAO;
import Modelo.Persona;
import Modelo.TipoPersona;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import Util.Render;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class FPersona extends javax.swing.JInternalFrame {

    TipoPersonaDAO tipoPersonaDAO = new TipoPersonaDAO();
    PersonaDAO personaDAO = new PersonaDAO();

    DefaultTableModel dtblPersona = null;
    JButton btnAModificar = new JButton("Editar");
    JButton btnADesactivar = new JButton("Desactivar");
    JButton btnAActivar = new JButton("Activar");
    JButton btnASeleccionar = new JButton("Seleccionar");
    SimpleDateFormat dtf = new SimpleDateFormat("yyyy/MM/dd");
    Persona oPersona = new Persona();

    DefaultComboBoxModel dcboTipoPersona = null;

    public FPersona() {
        initComponents();

        EstablecerFecha();
        habilitarBotones(true);

        oPersona.setEsActivo(true);
        buscarPersona(oPersona);

        listarTipoPersona();
    }

    private void EstablecerFecha() {
        Calendar calendarToday = Calendar.getInstance();
        Date dateObjToday = calendarToday.getTime();

        Calendar calendarBefore = Calendar.getInstance();
        calendarBefore.setTime(dateObjToday);
        calendarBefore.add(Calendar.MONTH, -1);

        Date dateObjBefore = calendarBefore.getTime();

        String today = dtf.format(dateObjToday);
        String before = dtf.format(dateObjBefore);
        try {
            Date fechaInicio = dtf.parse(before);
            Date fechaFin = dtf.parse(today);
            txtFechaInicio.setDate(fechaInicio);
            txtFechaFin.setDate(fechaFin);
        } catch (Exception ex) {

        }
    }

    public void inicializarPersona() {
        btnAModificar.setName("btnModificar");
        btnADesactivar.setName("btnDesactivar");
        btnAActivar.setName("btnActivar");

        tblPersona.setDefaultRenderer(Object.class, new Render());
        dtblPersona = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        dtblPersona.addColumn("IdPersona");
        dtblPersona.addColumn("NumeroDocumento");
        dtblPersona.addColumn("Nombres");
        dtblPersona.addColumn("Apellidos");
        dtblPersona.addColumn("Estado");
        dtblPersona.addColumn("");
        dtblPersona.addColumn("");
        tblPersona.setModel(dtblPersona);
        tblPersona.getTableHeader().setReorderingAllowed(false);
        tblPersona.getColumnModel().getColumn(0).setMaxWidth(0);
        tblPersona.getColumnModel().getColumn(0).setMinWidth(0);
        tblPersona.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblPersona.getColumnModel().getColumn(0).setResizable(false);
        tblPersona.setRowHeight(30);
    }

    public void buscarPersona(Persona oPersona) {

        inicializarPersona();
        List<Persona> lstCategoria = personaDAO.BuscarPersona(oPersona, txtFechaInicio.getDate(), txtFechaFin.getDate());

        for (int i = 0; i < lstCategoria.size(); i++) {
            dtblPersona.addRow(new Object[]{
                lstCategoria.get(i).getIdPersona(),
                lstCategoria.get(i).getNumeroDocumento(),
                lstCategoria.get(i).getNombres(),
                lstCategoria.get(i).getApellidoPaterno() + " " + lstCategoria.get(i).getApellidoMaterno(),
                lstCategoria.get(i).getEsActivo() ? "Activo" : "Desactivo",
                btnAModificar,
                lstCategoria.get(i).getEsActivo() ? btnADesactivar : btnAActivar
            });
        }
    }

    public void listarTipoPersona() {
        dcboTipoPersona = new DefaultComboBoxModel();
        cboTipoPersona.setModel(dcboTipoPersona);

        List<TipoPersona> lstCategoria = tipoPersonaDAO.listarTipoPersona();

        for (int i = 0; i < lstCategoria.size(); i++) {
            dcboTipoPersona.addElement(new TipoPersona(
                    lstCategoria.get(i).getIdTipoPersona(),
                    lstCategoria.get(i).getNombre()
            ));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBusqueda = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtFechaFin = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spPersona = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersona = new javax.swing.JTable();
        pDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cboTipoPersona = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();

        setClosable(true);

        pBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));
        pBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusqueda.setText("Búscar");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        pBusqueda.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 170, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Por Fecha Registro"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Fecha inicio");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 72, 20));
        jPanel4.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        jLabel12.setText("Fecha Fin");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        jPanel4.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 170, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 100, 30));

        pBusqueda.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 110));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Personas");

        tblPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersona);

        spPersona.setViewportView(jScrollPane1);

        pDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel3.setText("Nombres:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel4.setText("Apellido Paterno:");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel5.setText("Número de Documento:");

        jLabel6.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel6.setText("Celular:");

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel7.setText("Correo:");

        jLabel8.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel8.setText("Direccion:");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel11.setText("Tipo de persona:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jLabel2.setText("Apellid Materno");

        javax.swing.GroupLayout pDatosLayout = new javax.swing.GroupLayout(pDatos);
        pDatos.setLayout(pDatosLayout);
        pDatosLayout.setHorizontalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDatosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDatosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDatosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDatosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellidoMaterno)
                                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))))
                    .addGroup(pDatosLayout.createSequentialGroup()
                        .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pDatosLayout.setVerticalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(pDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed

    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        oPersona = new Persona();
        oPersona.setNumeroDocumento("");
        oPersona.setEsActivo(true);
        buscarPersona(oPersona);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonaMouseClicked
        int column = tblPersona.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblPersona.getRowHeight();

        if (row < tblPersona.getRowCount() && row >= 0 && column < tblPersona.getColumnCount() && column >= 0) {
            Object value = tblPersona.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("btnModificar")) {
                    habilitarBotones(false);
                    oPersona = new Persona();
                    oPersona.setIdPersona(Integer.parseInt(tblPersona.getValueAt(row, 0).toString()));
                    editarPersona();
                }
                if (boton.getName().equals("btnDesactivar")) {
                    Persona persona = new Persona();
                    persona.setEsActivo(false);
                    persona.setIdPersona(Integer.parseInt(tblPersona.getValueAt(row, 0).toString()));
                    int o = JOptionPane.showConfirmDialog(null, "Desea desactivar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    if (o == JOptionPane.YES_OPTION) {
                        eliminarPersona(persona);

                        persona = new Persona();
                        persona.setEsActivo(true);
                        buscarPersona(persona);
                    }
                }
                if (boton.getName().equals("btnActivar")) {
                    Persona persona = new Persona();
                    persona.setEsActivo(true);
                    persona.setIdPersona(Integer.parseInt(tblPersona.getValueAt(row, 0).toString()));
                    int o = JOptionPane.showConfirmDialog(null, "Desea activar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    if (o == JOptionPane.YES_OPTION) {
                        eliminarPersona(persona);

                        persona = new Persona();
                        persona.setEsActivo(true);
                        buscarPersona(persona);
                    }
                }
            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tblPersonaMouseClicked
      private void habilitarBotones(boolean activo) {
        btnRegistrar.setEnabled(activo);

        txtNumeroDocumento.setEditable(activo);
        btnModificar.setEnabled(!activo);
    }

    private String VerificarCampos() {
        //Verificar información
        if (txtNombre.getText().length() <= 0) {
            return "Nombre";
        }
        if (txtApellidoPaterno.getText().length() <= 0) {
            return "Apellido Paterno";
        }
        if (txtApellidoMaterno.getText().length() <= 0) {
            return "Apellido Materno";
        }
        if (txtNumeroDocumento.getText().length() <= 0) {
            return "Numero de Documento";
        }
        return "";
    }

    public void limpiar() {
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtNumeroDocumento.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        cboTipoPersona.setSelectedIndex(0);
        txtNombre.isFocusable();
    }

    private void editarPersona() {
        limpiar();

        oPersona = personaDAO.obtenerPersona(oPersona.getIdPersona());

        TipoPersona tipoPersona = new TipoPersona();
        tipoPersona.setIdTipoPersona(oPersona.getIdTipoPersona());
        cboTipoPersona.setSelectedItem(tipoPersona);
        txtNombre.setText(oPersona.getNombres());
        txtApellidoPaterno.setText(oPersona.getApellidoPaterno());
        txtApellidoMaterno.setText(oPersona.getApellidoMaterno());
        txtNumeroDocumento.setText(oPersona.getNumeroDocumento());
        txtCelular.setText(oPersona.getTelefono());
        txtCorreo.setText(oPersona.getCorreo());
        txtDireccion.setText(oPersona.getDireccion());

    }

    private void eliminarPersona(Persona persona) {
        boolean resp = personaDAO.eliminarPersona(persona);
        if (resp) {
            JOptionPane.showMessageDialog(null, (persona.getEsActivo() ? "Activado correctamente" : "Desactivado correctamente"), "Exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, (persona.getEsActivo() ? "Error al activar" : "Error al desactivar"), "Sin exito", JOptionPane.INFORMATION_MESSAGE);
        }
        habilitarBotones(true);
        limpiar();
    }
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            oPersona = new Persona();
            String nombre, apellidoPaterno, apellidoMaterno, numeroDocumento, celular, correo, direccion, validacion;

            validacion = VerificarCampos();

            if (!validacion.equals("")) {
                JOptionPane.showMessageDialog(null, "Verificar los datos en el campo " + validacion);
                return;
            }
            nombre = txtNombre.getText();
            apellidoPaterno = txtApellidoPaterno.getText();
            apellidoMaterno = txtApellidoMaterno.getText();
            numeroDocumento = txtNumeroDocumento.getText();
            celular = txtCelular.getText();
            correo = txtCorreo.getText();
            direccion = txtDireccion.getText();
            TipoPersona oTipoPersona = (TipoPersona) cboTipoPersona.getSelectedItem();

            oPersona.setIdTipoPersona(oTipoPersona.getIdTipoPersona());
            oPersona.setNombres(nombre);
            oPersona.setApellidoPaterno(apellidoPaterno);
            oPersona.setApellidoMaterno(apellidoMaterno);
            oPersona.setNumeroDocumento(numeroDocumento);
            oPersona.setTelefono(celular);
            oPersona.setCorreo(correo);
            oPersona.setDireccion(direccion);
            oPersona.setIdPersonaRegistro(1);

            boolean existe = personaDAO.existePersona(oPersona);
            if (existe) {
                JOptionPane.showMessageDialog(null, "Persona ya exite", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            boolean resp = personaDAO.registrarPersona(oPersona);

            if (resp) {
                limpiar();
                oPersona = new Persona();
                oPersona.setEsActivo(true);
                buscarPersona(oPersona);

                JOptionPane.showMessageDialog(null, "Persona registrada", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {

            String nombre, apellidoPaterno, apellidoMaterno, numeroDocumento, celular, correo, direccion, validacion;
            int idPersona = oPersona.getIdPersona();

            oPersona = new Persona();
            validacion = VerificarCampos();

            if (!validacion.equals("")) {
                JOptionPane.showMessageDialog(null, "Verificar los datos en el campo " + validacion);
                return;
            }

            nombre = txtNombre.getText();
            apellidoPaterno = txtApellidoPaterno.getText();
            apellidoMaterno = txtApellidoMaterno.getText();
            numeroDocumento = txtNumeroDocumento.getText();
            celular = txtCelular.getText();
            correo = txtCorreo.getText();
            direccion = txtDireccion.getText();
            TipoPersona oTipoPersona = (TipoPersona) cboTipoPersona.getSelectedItem();

            oPersona.setIdPersona(idPersona);
            oPersona.setIdTipoPersona(oTipoPersona.getIdTipoPersona());
            oPersona.setNombres(nombre);
            oPersona.setApellidoPaterno(apellidoPaterno);
            oPersona.setApellidoMaterno(apellidoMaterno);
            oPersona.setNumeroDocumento(numeroDocumento);
            oPersona.setTelefono(celular);
            oPersona.setCorreo(correo);
            oPersona.setDireccion(direccion);
            oPersona.setIdPersonaRegistro(1);

            //            boolean existe = personaDAO.existePersona(oPersona);
            //            if (existe) {
            //                JOptionPane.showMessageDialog(null, "Persona ya exite", "Info", JOptionPane.INFORMATION_MESSAGE);
            //                return;
            //            }
            boolean resp = personaDAO.modificarPersona(oPersona);

            if (resp) {
                limpiar();
                oPersona = new Persona();
                oPersona.setEsActivo(true);
                buscarPersona(oPersona);

                JOptionPane.showMessageDialog(null, "Persona modificada", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        habilitarBotones(true);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboTipoPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pBusqueda;
    private javax.swing.JPanel pDatos;
    private javax.swing.JScrollPane spPersona;
    private javax.swing.JTable tblPersona;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private com.toedter.calendar.JDateChooser txtFechaFin;
    private com.toedter.calendar.JDateChooser txtFechaInicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
