/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Persona;
import Util.Redimensionar;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author omar_
 */
public class Principal extends javax.swing.JFrame {

    public static Persona persona;

    public Principal() {
        initComponents();

        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    public Principal(Persona persona) {
        this.persona = persona;
        initComponents();

        mInfoUsuario.setText(persona.getNombres() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno());

        mBar.add(Box.createHorizontalGlue());
        mBar.add(mInfoUsuario);
        mBar.add(mSalir);
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsPrincipal = new javax.swing.JDesktopPane();
        mBar = new javax.swing.JMenuBar();
        mIncorporacion = new javax.swing.JMenu();
        mPersona = new javax.swing.JMenu();
        mInfoUsuario = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsPrincipal.setAutoscrolls(true);
        dsPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dsPrincipal.setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout dsPrincipalLayout = new javax.swing.GroupLayout(dsPrincipal);
        dsPrincipal.setLayout(dsPrincipalLayout);
        dsPrincipalLayout.setHorizontalGroup(
            dsPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        dsPrincipalLayout.setVerticalGroup(
            dsPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        mIncorporacion.setText("Incorporación");
        mIncorporacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mIncorporacion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        mIncorporacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mIncorporacionMouseClicked(evt);
            }
        });
        mBar.add(mIncorporacion);

        mPersona.setText("Persona");
        mPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mPersona.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        mPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPersonaMouseClicked(evt);
            }
        });
        mBar.add(mPersona);

        mInfoUsuario.setText("Info Usuario");
        mInfoUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mBar.add(mInfoUsuario);

        mSalir.setForeground(new java.awt.Color(255, 51, 51));
        mSalir.setText("Salir");
        mSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        mBar.add(mSalir);

        setJMenuBar(mBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIncorporacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mIncorporacionMouseClicked
        FIncorporacion fIncorporacion = new FIncorporacion();
        dsPrincipal.add(fIncorporacion);
        Redimensionar.redimensionar(dsPrincipal, fIncorporacion);
        fIncorporacion.show();
    }//GEN-LAST:event_mIncorporacionMouseClicked

    private void mPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPersonaMouseClicked
        FPersona fPersona = new FPersona();
        dsPrincipal.add(fPersona);
        Redimensionar.redimensionar(dsPrincipal, fPersona);
        fPersona.show();
    }//GEN-LAST:event_mPersonaMouseClicked

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        int o = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
        if (o == JOptionPane.YES_OPTION) {
            FLogin login = new FLogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dsPrincipal;
    private javax.swing.JMenuBar mBar;
    private javax.swing.JMenu mIncorporacion;
    private javax.swing.JMenu mInfoUsuario;
    private javax.swing.JMenu mPersona;
    private javax.swing.JMenu mSalir;
    // End of variables declaration//GEN-END:variables
}
